// <auto-generated />
using System;
using BusDrives.DataService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusDrives.DataService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("BusDrives.Entities.DbSet.BusDrive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverCompany")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinalCityId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RecurrenceEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceInterval")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StartingCityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FinalCityId");

                    b.HasIndex("StartingCityId");

                    b.ToTable("BusDrives");
                });

            modelBuilder.Entity("BusDrives.Entities.DbSet.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("BusDrives.Entities.DbSet.BusDrive", b =>
                {
                    b.HasOne("BusDrives.Entities.DbSet.City", "FinalCity")
                        .WithMany()
                        .HasForeignKey("FinalCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusDrives.Entities.DbSet.City", "StartingCity")
                        .WithMany()
                        .HasForeignKey("StartingCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinalCity");

                    b.Navigation("StartingCity");
                });
#pragma warning restore 612, 618
        }
    }
}
